#ifndef RPL_NUMERICAL_HPP
# define RPL_NUMERICAL_HPP

# define RPL_WELCOME			1     // 001 "Welcome to the Internet Relay Network"
# define RPL_YOURHOST			2     // 002 "Your host is ..., running version ..."
# define RPL_CREATED			3     // 003 "This server was created ..."
# define RPL_MYINFO				4     // 004 "Server info: <servername> <version> <usermodes> <chanmodes>"

# define RPL_AWAY				301   // 301 "<nick> :Away message"
# define RPL_UNAWAY				305   // 305 "You are no longer marked as being away"
# define RPL_NOWAWAY			306   // 306 "You have been marked as being away"
# define RPL_LIST				322   // 322 "<channel> <# visible> :<topic>"
# define RPL_LISTEND			323   // 323 ":End of LIST"
# define RPL_CHANNELMODEIS		324   // 324 "<channel> <mode> <mode params>"
# define RPL_NOTOPIC			331   // 331 "<channel> :No topic is set"
# define RPL_TOPIC				332   // 332 "<channel> :<topic>"
# define RPL_INVITING			341   // 341 "<nick> <channel>"
# define RPL_VERSION			351   // 351 "<version>.<debuglevel> <server> :<comments>"
# define RPL_WHOREPLY			352   // 352 "<channel> <user> <host> <server> <nick> <H|G>[*][@|+] :<hopcount> <real name>"
# define RPL_NAMREPLY			353   // 353 "( = / @ / * ) <channel> :[prefix]<nick> ..."
# define RPL_ENDOFNAMES			366   // 366 "<channel> :End of NAMES list"
# define RPL_MOTDSTART			375   // 375 ":- <server> Message of the day - "
# define RPL_MOTD				372   // 372 ":- <text>"
# define RPL_ENDOFMOTD			376   // 376 ":End of MOTD command."
# define RPL_YOUREOPER			381   // 381 ":You are now an IRC operator"
# define RPL_TIME				391   // 391 "<server> :<time string>"
# define RPL_INFO				371   // 371 ":<string>"
# define RPL_ENDOFINFO			374   // 374 ":End of INFO list"

# define ERR_NOSUCHNICK			401   // 401 "<nickname> :No such nick/channel"
# define ERR_NOSUCHSERVER		402   // 402 "<server> :No such server"
# define ERR_NOSUCHCHANNEL		403   // 403 "<channel> :No such channel"
# define ERR_CANNOTSENDTOCHAN	404   // 404 "<channel> :Cannot send to channel"
# define ERR_NORECIPIENT		411   // 411 ":No recipient given (<command>)"
# define ERR_NOTEXTTOSEND		412   // 412 ":No text to send"
# define ERR_UNKNOWNCOMMAND		421   // 421 "<command> :Unknown command"
# define ERR_NOMOTD				422   // 422 ":MOTD File is missing"
# define ERR_NONICKNAMEGIVEN	431   // 431 ":No nickname given"
# define ERR_ERRONEUSNICKNAME	432   // 432 "<nick> :Erroneous nickname"
# define ERR_NICKNAMEINUSE		433   // 433 "<nick> :Nickname is already in use"
# define ERR_USERNOTINCHANNEL	441   // 441 "<nick> <channel> :They aren't on that channel"
# define ERR_NOTONCHANNEL		442   // 442 "<channel> :You're not on that channel"
# define ERR_USERONCHANNEL		443   // 443 "<nick> <channel> :User already on channel"
# define ERR_NEEDMOREPARAMS		461   // 461 "<command> :Not enough parameters"
# define ERR_ALREADYREGISTRED	462   // 462 ":You may not reregister"
# define ERR_PASSWDMISMATCH		464   // 464 ":Password incorrect"
# define ERR_KEYSET				467   // 467 "<channel> :Channel key already set"
# define ERR_UNKNOWNMODE		472   // 472 "<char> :is unknown mode char to me"
# define ERR_INVITEONLYCHAN		473   // 473 "<channel> :Cannot join channel (+i)"
# define ERR_BADCHANNELKEY		475   // 475 "<channel> :Cannot join channel (+k)"
# define ERR_BADCHANMASK		476   // 476 "<channel> :Bad Channel Mask"
# define ERR_NOPRIVILEGES		481   // 481 ":Permission Denied- You're not an IRC operator"
# define ERR_CHANOPRIVSNEEDED	482   // 482 "<channel> :You're not channel operator"
# define ERR_CANTKILLSERVER		483   // 483 ":You can't kill a server!"

# define ERR_UMODEUNKNOWNFLAG	501   // 501 ":Unknown MODE flag"
# define ERR_USERSDONTMATCH		502   // 502 ":Cant change mode for other users"


#endif